// <auto-generated />
using System;
using KwikKwekSnack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KwikKwekSnack.Data.Migrations
{
    [DbContext(typeof(SnackContext))]
    [Migration("20221005174859_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KwikKwekSnack.Data.Drink", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ice")
                        .HasColumnType("bit");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Straw")
                        .HasColumnType("bit");

                    b.HasKey("Name");

                    b.HasIndex("OrderID");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Name = "Coca Cola",
                            Description = "Coca Cola",
                            Ice = false,
                            ImageURL = "~/img/coke.png",
                            Price = 1.5f,
                            Size = "S",
                            Straw = false
                        },
                        new
                        {
                            Name = "Fanta",
                            Description = "Fanta",
                            Ice = false,
                            ImageURL = "~/img/fanta.png",
                            Price = 1.5f,
                            Size = "M",
                            Straw = false
                        },
                        new
                        {
                            Name = "Pepsi",
                            Description = "Pepsi Cola",
                            Ice = false,
                            ImageURL = "~/img/pepsi.png",
                            Price = 1.5f,
                            Size = "L",
                            Straw = false
                        },
                        new
                        {
                            Name = "Coca Cola Zero",
                            Description = "Coca Cola Zero",
                            Ice = false,
                            ImageURL = "~/img/coke0.png",
                            Price = 1.5f,
                            Size = "XL",
                            Straw = false
                        },
                        new
                        {
                            Name = "Chocomel",
                            Description = "Chocomel",
                            Ice = false,
                            ImageURL = "~/img/choccy.png",
                            Price = 1f,
                            Size = "M",
                            Straw = false
                        },
                        new
                        {
                            Name = "Fristi",
                            Description = "Fristi",
                            Ice = false,
                            ImageURL = "~/img/fristi.png",
                            Price = 1f,
                            Size = "L",
                            Straw = false
                        },
                        new
                        {
                            Name = "Spa Rood",
                            Description = "Sprankelend water",
                            Ice = false,
                            ImageURL = "~/img/kutwater.png",
                            Price = 1f,
                            Size = "S",
                            Straw = false
                        },
                        new
                        {
                            Name = "Spa Blauw",
                            Description = "Water",
                            Ice = false,
                            ImageURL = "~/img/water.png",
                            Price = 1f,
                            Size = "S",
                            Straw = false
                        });
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Extra", b =>
                {
                    b.Property<string>("Extras")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SnackName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Extras");

                    b.HasIndex("SnackName");

                    b.ToTable("Extras");

                    b.HasData(
                        new
                        {
                            Extras = "Kaas"
                        },
                        new
                        {
                            Extras = "Ui"
                        },
                        new
                        {
                            Extras = "Sla"
                        },
                        new
                        {
                            Extras = "Tomaat"
                        });
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"), 1L, 1);

                    b.Property<bool>("TakeAway")
                        .HasColumnType("bit");

                    b.Property<string>("statuses")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderID");

                    b.HasIndex("statuses");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Size", b =>
                {
                    b.Property<string>("sizes")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("sizes");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            sizes = "S"
                        },
                        new
                        {
                            sizes = "M"
                        },
                        new
                        {
                            sizes = "L"
                        },
                        new
                        {
                            sizes = "XL"
                        });
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Snack", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Name");

                    b.HasIndex("OrderID");

                    b.ToTable("Snacks");

                    b.HasData(
                        new
                        {
                            Name = "Frikandel",
                            Description = "Frikandel",
                            ImageURL = "~/img/frikandel.png",
                            Price = 1.7f
                        },
                        new
                        {
                            Name = "Frikandel Speciaal",
                            Description = "Frikandel Speciaal",
                            ImageURL = "~/img/speciaal.png",
                            Price = 2.1f
                        },
                        new
                        {
                            Name = "Kroket",
                            Description = "Kroket",
                            ImageURL = "~/img/kroket.png",
                            Price = 1.7f
                        },
                        new
                        {
                            Name = "Kaassoufflé",
                            Description = "Kaassoufflé",
                            ImageURL = "~/img/kaas.png",
                            Price = 1.85f
                        },
                        new
                        {
                            Name = "Bamischijf",
                            Description = "Bamischijf",
                            ImageURL = "~/img/bami.png",
                            Price = 1.85f
                        },
                        new
                        {
                            Name = "Kipnuggets",
                            Description = "Kipnuggets",
                            ImageURL = "~/img/nuggets.png",
                            Price = 2.05f
                        },
                        new
                        {
                            Name = "Hamburger",
                            Description = "Hamburger",
                            ImageURL = "~/img/burger.png",
                            Price = 3.55f
                        },
                        new
                        {
                            Name = "Cheeseburger",
                            Description = "Cheeseburger",
                            ImageURL = "~/img/cburger.png",
                            Price = 4f
                        });
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Status", b =>
                {
                    b.Property<string>("statuses")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("statuses");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            statuses = "Wachtrij"
                        },
                        new
                        {
                            statuses = "Wordt bereid"
                        },
                        new
                        {
                            statuses = "Gereed"
                        });
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Drink", b =>
                {
                    b.HasOne("KwikKwekSnack.Data.Order", null)
                        .WithMany("Drinks")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Extra", b =>
                {
                    b.HasOne("KwikKwekSnack.Data.Snack", null)
                        .WithMany("Extras")
                        .HasForeignKey("SnackName");
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Order", b =>
                {
                    b.HasOne("KwikKwekSnack.Data.Status", "Status")
                        .WithMany()
                        .HasForeignKey("statuses")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Snack", b =>
                {
                    b.HasOne("KwikKwekSnack.Data.Order", null)
                        .WithMany("Snacks")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Order", b =>
                {
                    b.Navigation("Drinks");

                    b.Navigation("Snacks");
                });

            modelBuilder.Entity("KwikKwekSnack.Data.Snack", b =>
                {
                    b.Navigation("Extras");
                });
#pragma warning restore 612, 618
        }
    }
}
